yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [path('', views.index),
               path('group/<slug:slug>/',
                    views.group_posts,
                    name='group_list'), ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'), name='index'),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    """
    Класс Post используется для создания моделей Post
    (пост в социальной сети).
    """
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='postsin',
        blank=True,
        null=True,
    )

    class Meta:
        """
        Внутренний класс Meta для хранения метаданных
        класса Post.
        """
        ordering = ['-pub_date']


class Group(models.Model):
    """
    Класс Group используется для создания моделей Group
    сообществ, в которых происходит размещение постов
    в социальной сети.
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    """Information which is showing up on the start page."""
    posts = Post.objects.all()[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Information for displaying on the page with posts grouped by GROUPS."""
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}<!-- Вынуждена написать команду, т.к. в противном случае pytest не пропускает и выдает ошибку. -->
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
    <title>{% block title %}YaTube Последние обновления на сайте{% endblock %}</title>
  </head>
  <body>
    <header>  
      {% include 'includes/header.html' %}
    </header>
    <main> 
      {% block content %}
      {% endblock %}
    </main>       
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
    <footer class="border-top text-center py-3">
      <p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>

yatube/templates/includes/header.html
{% load static %}
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'img/logo.png' %}" width="30" height="30">
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>      
    </header>
    

yatube/templates/includes/post_feed.html
        <article>  
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{ post.text }}
          </p>
          {% if display_group_link and post.group %}
            <a
              href="{% url 'posts:group_list' slug=post.group.slug %}"
              class="btn btn-primary"
              target="_blank">все записи группы</a>
          {% endif %}
        </article>
        

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
    {% block title %}Записи сообщества {{ group }}{% endblock %}
      {% block content %}
      <div class="container py-5">
        <h1 class="card-header">{{ group }}</h1>
        <p>
          <span style="color:green"><i>{{ group.description }}</i></span>
        </p>
        {% for post in posts %}
        <article>
          {% include 'includes/post_feed.html' with display_group_link=False %}
        </article>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
      {% endblock %}
      

yatube/templates/posts/index.html
{% extends 'base.html' %}
    {% block title %}YaTube Последние обновления на сайте{% endblock %}
      {% block content %}
      <div class="container py-5">     
        <h1 class="card-header">Последние обновления на сайте</h1>
        {% for post in posts %}
        <article>
          {% include 'includes/post_feed.html' with display_group_link=True %}
        </article>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
      {% endblock %}